name: mi_card
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  url_launcher: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - images/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  fonts:
    - family: Amatic
      fonts:
        - asset: fonts/Amatic_SC/AmaticSC-Regular.ttf
        - asset: fonts/Amatic_SC/AmaticSC-Bold.ttf

    - family: Bangers
      fonts:
        - asset: fonts/Bangers/Bangers-Regular.ttf

    - family: Caveat
      fonts:
        - asset: fonts/Caveat/Caveat-Regular.ttf
        - asset: fonts/Caveat/Caveat-Bold.ttf

    - family: Kalam
      fonts:
        - asset: fonts/Kalam/Kalam-Regular.ttf
        - asset: fonts/Kalam/Kalam-Bold.ttf
        - asset: fonts/Kalam/Kalam-Light.ttf

    - family: PermanentMarker
      fonts:
        - asset: fonts/Permanent_Marker/PermanentMarker-Regular.ttf


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
